// ledger.test.ts — the golden fixtures: journals generated by quilt-core
// itself (Rust) must verify bit-for-bit through this TypeScript port,
// and tampering must be caught at the right sequence number.
import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import {
  parseJournal,
  verifyJournal,
  verifyChain,
  chainHash,
  genesisCommit,
  JournalError,
} from "../dist/ledger.js";

const FIX = join(import.meta.dirname, "fixtures");

async function fixture(name: string): Promise<string> {
  return readFile(join(FIX, name), "utf8");
}

// Golden chain hashes printed by the Rust fixture generator
// (/tmp/mm-fixtures, quilt-core CellLedger).
const GOLDEN: Record<string, string> = {
  "boat-1.jsonl": "7b8966bb190d942468daff4ecf89f1e669e71bf4e6d630368b0990fe9cadae54",
  "boat-2.jsonl": "67260417c540c1d95a409872bb20a83595eb87f0abbe8e07e347944990b37367",
  "boat-3.jsonl": "cf541a82a1b2ae9707c51ae216bec4559322a691a1e15231563dc043b23862a5",
  "empty-genesis.jsonl": "7de45a237f9bfc9f657d23b289cba780655a0f4fc1498811b863a1b3250b49df",
  "empty-void.jsonl": "6d51a1736e50331089b3e5cd47be2f84cc043fed0cf17f2d6f07a49a50be3a19",
};

for (const [name, golden] of Object.entries(GOLDEN)) {
  test(`golden: ${name} verifies bit-for-bit against quilt-core`, async () => {
    const journal = parseJournal(await fixture(name));
    const audit = verifyJournal(journal);
    assert.equal(audit.intact, true, audit.reason ?? "chain should be intact");
    assert.equal(audit.headerOk, true);
    assert.equal(chainHash(journal), golden);
  });
}

test("boat-1 exercises the float hazard (85.0, 77.5, 43.25 survive JS)", async () => {
  const j = parseJournal(await fixture("boat-1.jsonl"));
  assert.equal(j.entries.length, 3);
  assert.ok(j.entries[0].canonicalBody.includes('"before":40.0'), "40.0 stays a float");
  assert.ok(j.entries[2].canonicalBody.includes('"after":43.25'), "43.25 stays a float");
});

test("boat-2: genesis-less first entry carries no expected (no faked surprise); later ones do", async () => {
  const j = parseJournal(await fixture("boat-2.jsonl"));
  assert.equal(j.entries[0].expected, undefined); // no prior -> no claim
  assert.notEqual(j.entries[1].expected, undefined); // persistence prior recorded
});

test("empty ledgers: chain_hash equals the genesis commit", async () => {
  for (const name of ["empty-genesis.jsonl", "empty-void.jsonl"]) {
    const j = parseJournal(await fixture(name));
    assert.equal(j.entries.length, 0);
    assert.equal(chainHash(j), genesisCommit(j.header));
    assert.ok(verifyJournal(j).intact);
  }
});

test("tamper: editing an output value breaks the chain at that seq", async () => {
  const text = await fixture("boat-1.jsonl");
  const lines = text.split("\n");
  const tampered = lines
    .map((l, i) => (i === 2 ? l.replace('"value":77.5', '"value":99.5') : l))
    .join("\n");
  const j = parseJournal(tampered);
  const audit = verifyChain(j);
  assert.equal(audit.intact, false);
  assert.equal(audit.firstBreak, 2);
});

test("tamper: 77.5 → 77.5 as INTEGER (float erasure) breaks the seal", async () => {
  const text = await fixture("boat-1.jsonl");
  const j = parseJournal(text.replace('"after":77.5', '"after":77.50'));
  // 77.50 normalizes to 77.5 — the canonical form forgives redundant
  // zeros, so this edit does NOT change the hash... but the matching
  // input.value stays 77.5; only delta.after changed lexeme.
  // Instead erase the float marker outright:
  const j2 = parseJournal(text.replace('"before":85.0', '"before":85'));
  const audit = verifyChain(j2);
  assert.equal(audit.intact, false);
  assert.equal(audit.firstBreak, 2);
});

test("tamper: swapping a prev_hash link is caught at the next entry", async () => {
  const text = await fixture("boat-3.jsonl");
  const lines = text.split("\n");
  const evil = lines[1].replace(
    /"prev_hash":"[0-9a-f]{64}"/,
    '"prev_hash":"' + "0".repeat(64) + '"',
  );
  const j = parseJournal([lines[0], evil, lines[2]].join("\n"));
  const audit = verifyChain(j);
  assert.equal(audit.intact, false);
  assert.equal(audit.firstBreak, 1);
});

test("tamper: stale header chain_hash is reported (headerOk false)", async () => {
  const text = await fixture("boat-1.jsonl");
  const lines = text.split("\n").slice();
  // drop the last entry but keep the header claiming 3 entries? — parse
  // rejects that. Instead: append a valid extra record is impossible
  // without keys; so simulate staleness by editing the header hash.
  const staleHeader = lines[0].replace(
    /"chain_hash":"[0-9a-f]{64}"/,
    '"chain_hash":"' + "f".repeat(64) + '"',
  );
  const j = parseJournal([staleHeader, ...lines.slice(1)].join("\n"));
  const audit = verifyJournal(j);
  assert.equal(audit.intact, true); // the chain itself is honest…
  assert.equal(audit.headerOk, false); // …but the header lies
});

test("rejects: wrong journal kind", async () => {
  const text = await fixture("boat-1.jsonl");
  const bad = text.replace("quilt-cell-ledger-journal/1", "someone-elses-journal/7");
  assert.throws(() => parseJournal(bad), JournalError);
});

test("rejects: header/entry count mismatch", async () => {
  const text = await fixture("boat-1.jsonl");
  const bad = text.replace('"entries":3', '"entries":2');
  assert.throws(() => parseJournal(bad), /header says 2 entries but journal carries 3/);
});

test("rejects: empty file", () => {
  assert.throws(() => parseJournal(""), JournalError);
});
